### ISSUE TITLE
ForceBypass

### ISSUE THREAD

**Issue by scottleestrange** [node-alarm-dot-com/homebridge-node-alarm-dot-com#76] opened 2021-05-23 19:59 UTC
**Is your feature request related to a problem? Please describe.**
We cannot leave upstairs windows open at night and use the plugin

**Describe the solution you'd like**
Concord 4 Panels as well as others have a ForceBypass option that allows the panel to bypass all open sensors

We should have a ForceBypass property that will send the ForceBypass.  

We should also have more options for Arming Modes, we should have the option of defining the name of the switch positions as well as their actions

Example:
  "armingModes" : {
    "away" : {
     "name":"Away",
      "noEntryDelay" : false,
      "silentArming" : false
    },
    "night" : {
     "name":"Sleep",
      "noEntryDelay" : true,
      "silentArming" : true
    },
    "night-bypass" : {
      "name":"Sleep Bypass",
      "noEntryDelay" : true,
      "silentArming" : true
    },
    "stay" : {
     "name": "Stay"
      "noEntryDelay" : false,
      "silentArming" : false
    }
  
You can provide to be able to change the name for the off position, os simply leave that as required and cannot change.  The current button name as off is intuitive to all.  But we should be able to define what switch positions exist and their names as well as the properties.

**Describe alternatives you've considered**
At lease please implement ForceBypass.  I can live with always configuring night with force bypass.  I will get notifications on what is bypassed form alarm.com

**Additional context**

**Comment by ngori** [comment] 2021-05-23 23:44
@scottleestrange Are you able to set Force Bypass from the alarm.com app or are you only able to set it from your panel? What does the alarm.com app show when in this Forced Bypass mode? I have a qolsys panel so my setup is a bit different. If I arm the system with an open sensor it is automatically bypassed until the system is disarmed and the sensor closed and the rearmed. Is that not the case for you?

I can also selectively bypass a sensor that may already be closed from the panel but I can't do that from the app.

**Comment by scottleestrange** [comment] 2021-05-24 00:10
When I set arm stay on alarm.com. I have the options of silent arming, No Entry Delay and Force Bypass. 

![image](https://user-images.githubusercontent.com/83140102/119281243-d299c900-bbe9-11eb-992c-2557d51547e7.jpeg)

**Comment by ngori** [comment] 2021-05-24 01:29
I believe the HomeKit Security System accessory type only supports arm stay, arm night, arm away, and disarm.  You could try forking and repurposing arm night to pass the arguments for force bypass.

**Comment by scottleestrange** [comment] 2021-05-24 02:13
But the plug-in needs to support the force bypass. If you see in my request

**Comment by ngori** [comment] 2021-05-25 17:29
Hi.  Yup, I understand the request.  Just it seems like a very limited use case.  I can't assist as my panel doesn't support force bypass or it may but I use an auto bypass for any open sensors/zones.  You should be able to watch the api call while initiating a force bypass in a browser and then just dump the parameters into night arm lines 109-112 in index.ts on a fork and be good to go.

**Comment by scottleestrange** [comment] 2021-05-25 18:44
If you look back, I am not the first to ask for this.  I am not convinced it is a limited use case

My experience is not web development, I have many years of backend development.  Not sure how to do what you ask for me to make the changes

**Comment by scottleestrange** [comment] 2021-05-25 18:49
I am also new to GitHub.  I see where you are saying to make the change.  But I am not familiar with the interface of GitHub to check out the code.  Also form what I see others are already working on Beta releases on this code

**Comment by ngori** [comment] 2021-06-20 19:05
@scottleestrange are you able to join the homebridge discord?  I'll help you over there on the node-alarm-dot-com channel.

**Comment by jibelin** [comment] 2021-07-07 05:34
I too would appreciate some help with implementing Force Bypass.  I confirmed it is supported directly with Alarm.com as web and mobile applications and can see the variable forceBypass sent via the web.  But I cannot figure out how to pass or send this via the Homebridge AlarmDotCom plugin.  Any help would be appreciated...

**Comment by ngori** [comment] 2021-07-07 12:48
@jibelin.  Take a look at lines 105-117 on the current release  src/index.ts.  If you want to repurpose night arm to Force Bypass as mentioned above you would need add "forceBypass: true" and see if that results in your expected arming behavior.  I don't have forceBypass as an arming mode with my panel so I can't test this for you.

**Comment by jibelin** [comment] 2021-07-07 14:04
> @jibelin. Take a look at lines 105-117 on the current release src/index.ts. If you want to repurpose night arm to Force Bypass as mentioned above you would need add "forceBypass: true" and see if that results in your expected arming behavior. I don't have forceBypass as an arming mode with my panel so I can't test this for you.

Thanks for the quick reply - I’ve been reading and trying to learn how to make the edits and install the updated package into Homebridge.  is there a recommendation on approach to just edit this one file and install it into the existing package or do I need to figure out how to publish to npm

**Comment by ngori** [comment] 2021-07-07 14:34
The better way is to fork the project on github make the edits on your fork and install your fork with npm. That being said, when I was working on the garage door implementation I just edited the few fieles on my locally installed packages and rebooted hombridge constantly to test.

**Comment by jibelin** [comment] 2021-09-06 04:38
> @jibelin. Take a look at lines 105-117 on the current release src/index.ts. If you want to repurpose night arm to Force Bypass as mentioned above you would need add "forceBypass: true" and see if that results in your expected arming behavior. I don't have forceBypass as an arming mode with my panel so I can't test this for you.

I tried the above and it does not appear to send the commands in the code tried with the previous version not sure if @chase9 may be able to look into this with the most recent updated version?  This would be an amazing addition - i could call it a bug as it is supported on the alarm.com web portal...

**Comment by chase9** [comment] 2022-02-09 20:12
@jibelin Just an FYI, a bug would be a defect in existing functionality, so this would be an enhancement request :)

@scottleestrange This is a simple add, but I don't have a panel that can take advantage of this so I have no way of investigating or testing. I would need you to look at the AJAX request that's sent to alarm.com when you attempt to arm the alarm with the desired settings. If you look at the JSON payload on the request, there should be an option like `forceBypass: true` which is what I need.

**Comment by jibelin** [comment] 2022-02-09 21:02
thank you for looking into this - fair point about a bug against current functionality so you're right it fair to call it an enhancement ;-)  Appreciate your help, let me know if there is something I can to help - possibly test if required...

**Comment by scottleestrange** [comment] 2022-10-03 13:14
@chase9 How do I look at the AJAX request?

**Comment by DouweM** [comment] 2024-11-29 02:04
@chase9 Looks like you had a chance to add this to node-alarm-dot-com last year! https://github.com/node-alarm-dot-com/node-alarm-dot-com/commit/1d61dee53360a946e1b0639f1cd101cf0243627e

I believe adding support to the Homebridge plugin would be a matter of editing 

https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/blob/31133b4326e1c431437c55f3783c819e6d468e25/src/index.ts#L141-L166

and

https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/blob/31133b4326e1c431437c55f3783c819e6d468e25/src/index.ts#L674-L692

Plus docs.

I can put a PR together if you'd accept one!

**Comment by chase9** [comment] 2024-12-14 19:52
Merged into v1.10.2. Thank you!

**Closed by chase9** 2024-12-14 19:52 UTC
Labels: enhancement
