### ISSUE TITLE
New issue with two-factor authentication?

### ISSUE THREAD

**Issue by ansuz07** [node-alarm-dot-com/homebridge-node-alarm-dot-com#64] opened 2021-03-15 11:02 UTC
**Describe the bug**

New error started getting thrown last night:

Error: No afg cookie: ASP.NET_SessionId=mjga3owfch2vx1gu5slqkfjh; cookieTest=1; twoFactorAuthenticationId=A52744CA5C23C11C8646207F7F002249F432706A21A45D148CF7DBEA211F7040; IsFromNewSite=1; fromASP=; IsFromSeamlessLogin=; login=; ST=; SeamlessLoginEnabled=; loggedInAsSubscriber=1; twoFactorAuthenticationSkipped-9161925=false; BIGipServer~AlarmApplication~Alarm_WEBADC_Alarm_HTTPS=!eXBsN/cPvApadKXNzUFX+zqT5KjmGKSumY7YHPL1lnyrcS0E0tWMQdgVBRbqBtgDUSRVRUT9/3f9pCs=
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:91:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**To Reproduce**

No behavior - error is thrown automatically.  System is unresponsive

**Expected behavior**
System can log into ADC

**Homebridge System (please complete the following information):**
* **Node.js Version**: 14.6.0
* **NPM Version**:6.14.11
* **Homebridge Version**:1.3.3
* **Operating System**: Ubuntu
* **Process Supervisor**: Systemd

**Comment by chase9** [comment] 2021-03-15 13:53
Duplicate of https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/11

Check that thread for more details and how to test the beta version which adds support for 2FA.

**Closed by chase9** 2021-03-15 13:53 UTC
Labels: bug, duplicate
