### ISSUE TITLE
"read ECONNRESET" errors in log

### ISSUE THREAD

**Issue by jfmach** [node-alarm-dot-com/homebridge-node-alarm-dot-com#65] opened 2021-03-18 15:56 UTC
**Describe the bug**
The following is logged in homebridge.log:
[18/03/2021, 11:50:10] [Alarmdotcom] UNHANDLED ERROR: Error: GET https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=100792472-21&ids%5B%5D=100792472-28&ids%5B%5D=100792472-24&ids%5B%5D=100792472-4&ids%5B%5D=100792472-29&ids%5B%5D=100792472-16&ids%5B%5D=100792472-5&ids%5B%5D=100792472-3&ids%5B%5D=100792472-20&ids%5B%5D=100792472-17&ids%5B%5D=100792472-18&ids%5B%5D=100792472-26&ids%5B%5D=100792472-25&ids%5B%5D=100792472-19&ids%5B%5D=100792472-22&ids%5B%5D=100792472-8&ids%5B%5D=100792472-9&ids%5B%5D=100792472-11&ids%5B%5D=100792472-7&ids%5B%5D=100792472-6&ids%5B%5D=100792472-12&ids%5B%5D=100792472-23&ids%5B%5D=100792472-10&ids%5B%5D=100792472-14&ids%5B%5D=100792472-13&ids%5B%5D=100792472-27&ids%5B%5D=100792472-15&ids%5B%5D=100792472-5514&ids%5B%5D=100792472-5513&ids%5B%5D=100792472-229 failed: request to https://www.alarm.com/web/api/devices/sensors?ids%5B%5D=100792472-21&ids%5B%5D=100792472-28&ids%5B%5D=100792472-24&ids%5B%5D=100792472-4&ids%5B%5D=100792472-29&ids%5B%5D=100792472-16&ids%5B%5D=100792472-5&ids%5B%5D=100792472-3&ids%5B%5D=100792472-20&ids%5B%5D=100792472-17&ids%5B%5D=100792472-18&ids%5B%5D=100792472-26&ids%5B%5D=100792472-25&ids%5B%5D=100792472-19&ids%5B%5D=100792472-22&ids%5B%5D=100792472-8&ids%5B%5D=100792472-9&ids%5B%5D=100792472-11&ids%5B%5D=100792472-7&ids%5B%5D=100792472-6&ids%5B%5D=100792472-12&ids%5B%5D=100792472-23&ids%5B%5D=100792472-10&ids%5B%5D=100792472-14&ids%5B%5D=100792472-13&ids%5B%5D=100792472-27&ids%5B%5D=100792472-15&ids%5B%5D=100792472-5514&ids%5B%5D=100792472-5513&ids%5B%5D=100792472-229 failed, reason: read ECONNRESET
    at /usr/local/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/dist/index.js:466:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
    at async Promise.all (index 0)

**To Reproduce**
No steps, this happens in the logs regularly. No action in Homekit.

**Expected behavior**
No error (or handled error)

**Screenshots**
N/A

**ADC-SystemStates.json**
[ADC-SystemStates.txt](https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/files/6165423/ADC-SystemStates.txt)

**Homebridge System (please complete the following information):**
* **Node.js Version**: v14.15.5
* **NPM Version**: 7.5.4
* **Homebridge Version**: 1.3.4
* **Operating System**: Debian 10.8
* **Process Supervisor**: hb-service

**Additional context**
N/A

**Comment by jfmach** [comment] 2021-03-19 16:23
Hi there,

I should mention, this seems to be happening every 2 minutes. Not systematically so maybe some of the calls do succeed?

**Comment by chase9** [comment] 2021-03-21 15:17
Hi jfmach, I'm going to track all these in one thread so please take a look there.

Duplicate of #63

**Closed by chase9** 2021-03-21 15:17 UTC
Labels: bug, duplicate
